### PR TITLE
Use of shortcuts detected & use the mouse to take object

### PR DESCRIPTION
**Pull request by rickoff**
object usage in the shortcut bar is not detected in function :
eventHandler.OnPlayerEquipment
eventHandler.OnPlayerItemUse
(this prevents creating functional scripts because it can be bypassed by the player using the shortcut it's annoying)

objects retrieved using the mouse when the inventory is open are not detected in function :
eventHandler.OnObjectActivate
(same problem here with the recovery of a prohibited object for example)

there are workarounds to succeed but it always involves twisted things

### CODE REVIEW

**Comment by uramer** [comment]
I think you've made a PR to the wrong branch
as you can see, you are also asking to merge a bunch of older commits by other people into master
most likely, your PS is meant for 0.7.0 branch, or maybe 0.7.1

**Comment by rickoff** [comment]
my very first request on git is it good like that?

**Comment by uramer** [comment]
If you look at the commits included in your PR, you will see you are also merging some of David's changes from 0.7.1 to 0.7.0.
If you want to submit a change to 0.7.0, you need to start with 0.7.0 branch.
Your PR is based on 0.7.1, so you also grabbed some changes present in it, together with yours.
You might have to remake your commits, using current 0.7.0 as a base.
But maybe wait for what David thinks about this PR first.

**Comment by davidcernat** [comment]
I have no idea what you're trying to do here. All the commits in this pull requests are by me and have no relation to the topic of this pull request.

Maybe you were trying to start an issue instead?

**Pull request closed without merging**
