### PR TITLE
LDOC documentation

### PR DESCRIPTION
**Pull request by 1338**
The documentation I had been talking about.
It's probably not perfect yet (I'm human after all) but I though I'd drop it in now before I have to manage any merge conflict. So now you can decide if you like it. :+1: 

The docs can be generated in the main folder by issuing `ldoc .` (the configuration is in config.ld, might have to adjust `file = '../server'` to whatever the repository is called on your local machine).
I already have them generated in /docs so you can open the index.html to have a looksy.
The syntax of LDoc can be found at https://stevedonovan.github.io/ldoc/manual/doc.md.html

### CODE REVIEW

**Comment by davidcernat** [comment]
Can you please tell me what the ratio of documentation to code would be after merging this in?

**Comment by 1338** [comment]
Well due to the hooks system there is more inflation of documentation strings to code then I'd like.
For example in serverCore.lua:
```lua
--- On object state
-- @int pid player ID
-- @string cellDescription
function OnObjectState(pid, cellDescription)
-- removed for brevity
end
```
But in eventHandler I documented it again:
```lua
--- On object state
-- @int pid player ID
-- @string cellDescription cell name
function eventHandler.OnObjectState(pid, cellDescription)
-- removed for brevity
end
```
I could probably get it down by about ~500 SLOC by removing those from serverCore.lua, removing the generated docs folder will probably shave off another ~20000 SLOC, html isn't a very SLOC efficient language.

Also because lua isn't statically typed some LDoc gets rather heavy on functions with many inputs:
```lua
--- Build AI data
-- @int targetPid target player ID
-- @param targetUniqueIndex
-- @param action
-- @int posX
-- @int posY
-- @int posZ
-- @int distance
-- @param duration
-- @bool shouldRepeat
```

The docs cover everything except:
- Menus (not really possible to document with LDoc due how to Menus are formatted in `server/scripts/menu/`)
- speechHelper/speechCollections, just noticed I forgot these, my bad

Or do you mean the pure code vs. docs SLOC? There are about 1/4 the amount of lines used for docs as there is code. (A lot of 3 lines functions are 1:1 code to doc strings, also not counting /docs/)

I could also document the speech 'modules', remove generated docs from the PR then make a new PR so the added SLOC is more truthful to the actual amount, if you'd like that?

**Comment by davidcernat** [comment]
I'll merge this in if:

1) You remove the commit with the generated .html files from the commit history. They have no place in this Lua-only repository.

2) You fix the parameter types for the functions. A decent number of them are just wrong. For example, the refIds of objects and IDs of records are mistakenly listed as integers instead of strings [here](https://github.com/TES3MP/CoreScripts/pull/76/commits/38a33532c7415ba5b43ed244918b5ef99a07cff5).

3) You fix the various typos and instances of weird capitalization.


I'm also going to request that you use the present tense for the verbs in your commit names from now on (i.e. in future pull requests), to stay consistent with [common usage](https://stackoverflow.com/questions/3580013/should-i-use-past-or-present-tense-in-git-commit-messages).

**Comment by 1338** [comment]
I guess I made some mistakes with this pull:
1. I should have messaged you the repo on discord instead of an pull request
2. I should have clearly stated this was an example of how it would look
3. I have no excuses for my poor git commit practice, it's just horrible. I'll watch it more closely next time.

I'll close this, once I have actually done it (writing all the LDoc properly, adding usage examples, etc) I will open a pull request where I actually want to merge.

**Comment by davidcernat** [comment]
You can split it up into smaller pull requests if you like.

**Pull request closed without merging**
